Codigo para Utilizar Ataque2 en NPC
ao-org/argentum-online-server pull request #579
Opened 2024-05-03 00:44 UTC by plusin

2024-05-03 01:10 UTC, RecoX commented on Server.VBP
> -Object={6B7E6392-850A-101B-AFC0-4210102A8DA7}#1.3#0; comctl32.ocx
Eliminar cambios en este archivo.

2024-05-03 01:12 UTC, plusin reviewed
Listo

2024-05-03 01:12 UTC, RecoX commented on Server.VBP
> -RevisionVer=38
Eliminar cambios en vbp

2024-05-03 01:13 UTC, RecoX requested changes
eliminar cambios en vbp

2024-05-04 06:47 UTC, plusin reviewed
ok

2024-05-04 07:13 UTC, plusin reviewed
OK

2025-01-18 00:49 UTC, closed without merging