El apostador
ao-org/argentum-online-server pull request #581
Opened 2024-05-04 07:13 UTC by plusin

Probar con NPC

2024-05-04 22:56 UTC, RecoX commented on Codigo/Protocol_GmCommands.bas
> -116         ElseIf NpcList(.flags.TargetNPC.ArrayIndex).npcType <> e_NPCType.Timbero Then
No borrar esta validacion

2024-05-04 22:57 UTC, RecoX requested changes
No borrar la validacion

2024-11-18 17:44 UTC, plusin commented
Por favor revisa si ahora esta todo bien!

2024-11-19 01:53 UTC, RecoX commented
Hay conflictos en ` Codigo/Protocol_GmCommands.bas` y hay mas de 300 lineas cambiadas

2024-11-19 02:00 UTC, closed without merging