Update Protocol_GmCommands.bas
ao-org/argentum-online-server pull request #656
Opened 2024-11-19 02:14 UTC by plusin

Ajustamos porcentajes y apuesta minima.

2024-11-20 20:10 UTC, morgolock requested changes
Por favor cambia el titulo del commit por algo mas descriptivo

`Update Protocol_GmCommands.bas` no es descriptivo

2024-11-20 20:51 UTC, plusin commented
> Por favor cambia el titulo del commit por algo mas descriptivo
> 
> `Update Protocol_GmCommands.bas` no es descriptivo

Listo, gracias =)

2024-11-20 21:29 UTC, morgolock requested changes
En el mensaje del commit por favor agregar esto

> Se cambia el valor de apuesta máxima de 10.000 monedas a 5.000 monedas
Se ajusta el porcentaje de probabilidades de ganar porque estaba muy elevado

2024-11-21 18:34 UTC, morgolock approved these changes

2024-11-21 19:47 UTC, RecoX approved these changes

2024-11-21 19:48 UTC, merged