Apuñalar
ao-org/argentum-online-server pull request #658
Opened 2024-11-19 23:30 UTC by Temis-gt

2024-11-19 23:34 UTC, ao-20 commented
Fellow citizen of Nix, one of the admins verify this pull request

2024-11-20 01:14 UTC, RecoX requested changes

2024-11-20 01:14 UTC, RecoX commented on Codigo/SistemaCombate.bas
> +                    Else
Este Else no deberia de existir, ya que no hay ninguna logica dentro de el mismo.

2024-11-20 20:06 UTC, morgolock commented
El titulo del commit Apuñalar no es descriptivo

Por favor cambiar el titulo y el mensaje en el commit explicando el cambio en palabras

2024-11-20 20:08 UTC, morgolock requested changes
Por favor explicar en el mensaje de commit el cambio.
Se remueve bastante logica al quitar el codigo
```
  ' Si el daño total es superior a su vida maxima, lo dejamos en uno de vida y mostrar un mensaje por consola
                    Select Case Damage
                        Case Is >= .Stats.MaxHp * 1.1
                            Damage = .Stats.MinHp
                        Case Is < .Stats.MaxHp * 1.1 And Damage >= .Stats.MaxHp
                            Damage = .Stats.MinHp - 1
                            'Enviamos mensaje al atacante
                            Call WriteConsoleMsg(AtacanteIndex, "Has dejado agonizando a tu oponente", e_FontTypeNames.FONTTYPE_INFOBOLD)
                            'Enviamos mensaje a la victima
                            Call WriteConsoleMsg(VictimaIndex, "Has quedado agonizando", e_FontTypeNames.FONTTYPE_INFOBOLD)
                        Case Else
                            ' Sino, restamos el daño normalmente
                    End Select
```

2024-11-21 07:27 UTC, morgolock approved these changes

2024-11-21 19:46 UTC, RecoX approved these changes

2024-11-21 19:47 UTC, merged